

service: bootstrapper

custom:
  defaults:
    stage: localdev
    region: eu-west-1
    profile: local
    domain: ${opt:apidomain, "${self:custom.defaults.apidomain}"}
  config:
    stage: ${opt:stage,"${self:custom.defaults.stage}"}
    profile: ${opt:profile, "${self:custom.defaults.profile}"}
    region: ${opt:region, "${self:custom.defaults.region}"}
    domain: ${opt:domain, "${self:custom.defaults.domain}"}
  customDomain:
    domainName: ${self:custom.config.domain}
    stage: ${self:custom.config.stage}
    basePath: ${self:custom.config.stage}
    certificateName: '*.api.ccoherence.com'
    createRoute53Record: true
    endPointType: 'regional'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  profile: ${self:custom.config.profile}

functions:
  deviceAdd:
    handler: handler.deviceAdd
    events:
      - http:
         path: device
         method: post
  deviceDelete:
    handler: handler.deviceDelete
    events:
      - http:
         path: device/{id}
         method: delete
  deviceGetAll:
    handler: handler.deviceGetAll
    events:
      - http:
         path: device
         method: get

  deviceGetOne:
    handler: handler.deviceGetOne
    events:
      - http:
         path: device/{id}
         method: get
